name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main  # Triggers deployment when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Triggers deployment when a PR is merged into 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up SSH for deployment
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      # Step 3: Copy frontend files to VPS
      - name: Copy files to VPS
        run: |
          scp -r ./node-react-pos/frontoffice root@${{ secrets.SERVER_IP }}:/var/www/pos_react_front_office

      # Step 4: SSH into VPS and deploy
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            cd /var/www/pos_react_front_office
            docker-compose up -d --build frontend  # Only restart the frontend container
          EOF
