name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main  # Deploy when code is pushed to 'main'
  pull_request:
    branches:
      - main  # Deploy when a PR is merged into 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full repo is cloned

      # Step 2: Debug - Check files in workspace
      - name: Debug - List files in workspace
        run: |
          echo "Current Directory:"
          pwd
          echo "Listing files:"
          ls -la

      # Step 3: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      # Step 4: Copy frontend files to VPS
      - name: Copy files to VPS
        run: |
          echo "Checking for the correct directory..."
          if [ -d "$GITHUB_WORKSPACE/pos_react_front_office" ]; then
            echo "Found pos_react_front_office at $GITHUB_WORKSPACE/pos_react_front_office"
            scp -r $GITHUB_WORKSPACE/pos_react_front_office root@${{ secrets.SERVER_IP }}:/var/www/pos_react_front_office
          else
            echo "Error: pos_react_front_office directory not found!"
            ls -la $GITHUB_WORKSPACE  # Debug: List files
            exit 1
          fi

      # Step 5: SSH into VPS and restart frontend
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            cd /var/www/pos_react_front_office
            docker-compose up -d --build frontend  # Restart frontend container only
          EOF
